<script setup>
import { Head, Link, useForm, usePage } from '@inertiajs/vue3';
import AppLayout from '../../Layouts/AppLayout.vue';
import TournamentCard from '../../Components/tournaments/TournamentCard.vue';
import Button from '../../Components/common/Button.vue';
defineProps({ tournaments: Object });
const page = usePage();
const form = useForm({ name: '', venue: '', starts_on: '', ends_on: '', timezone: 'Asia/Tehran' });
const submit = () => form.post(page.props.urls.tournaments);
</script>
<template>
    <AppLayout><Head title="مسابقات" />
        <section class="mb-[30px] flex items-center justify-between gap-5 max-[760px]:flex-col max-[760px]:items-start max-[760px]:gap-[15px]"><div><span class="mb-2 block text-xs text-[#578678]">مدیریت رویدادها</span><h1 class="text-[29px] font-bold leading-[1.6] max-[760px]:text-[25px]">مسابقات</h1><p class="mt-2 text-[13px] text-[#7c8984]">هر رویداد، رده‌ها و اعضای تیم برگزاری مستقل خود را دارد.</p></div></section>
        <section v-if="page.props.auth.user.is_admin" class="mb-6 rounded-xl border border-[#e2e9df] bg-white p-[27px] max-[760px]:p-5"><h2 class="mb-5 text-lg font-bold">تعریف مسابقه</h2><form @submit.prevent="submit" class="mt-[18px] grid grid-cols-1 gap-[18px] min-[761px]:grid-cols-3"><div class="min-[761px]:col-span-3"><label class="mb-[7px] block text-xs text-[#63756b]" for="name">نام مسابقه</label><input id="name" v-model="form.name" class="min-h-11 w-full rounded-[7px] border border-[#dce5da] bg-[#fcfdfa] px-3 py-[10px] text-[#253c31] focus:outline-2 focus:outline-[#79a28b]" required maxlength="255" placeholder="مثلاً مسابقات قهرمانی استان"></div><div><label class="mb-[7px] block text-xs text-[#63756b]" for="venue">محل برگزاری</label><input id="venue" v-model="form.venue" class="min-h-11 w-full rounded-[7px] border border-[#dce5da] bg-[#fcfdfa] px-3 py-[10px] text-[#253c31] focus:outline-2 focus:outline-[#79a28b]" maxlength="255" placeholder="نام سالن"></div><div><label class="mb-[7px] block text-xs text-[#63756b]" for="starts">تاریخ شروع (میلادی)</label><input id="starts" v-model="form.starts_on" class="min-h-11 w-full rounded-[7px] border border-[#dce5da] bg-[#fcfdfa] px-3 py-[10px] text-[#253c31] focus:outline-2 focus:outline-[#79a28b]" type="date" required dir="ltr"></div><div><label class="mb-[7px] block text-xs text-[#63756b]" for="ends">تاریخ پایان (اختیاری)</label><input id="ends" v-model="form.ends_on" class="min-h-11 w-full rounded-[7px] border border-[#dce5da] bg-[#fcfdfa] px-3 py-[10px] text-[#253c31] focus:outline-2 focus:outline-[#79a28b]" type="date" :min="form.starts_on" dir="ltr"></div><div class="flex flex-wrap items-center gap-5 min-[761px]:col-span-3"><Button type="submit" :disabled="form.processing">{{ form.processing ? 'در حال ثبت…' : 'ساخت مسابقه' }}</Button><span class="text-[13px] text-[#7c8984]">منطقهٔ زمانی: تهران</span></div><div v-if="Object.keys(form.errors).length" class="min-[761px]:col-span-3 mt-1.5 text-xs text-[#a33939]" role="alert"><p v-for="(error, key) in form.errors" :key="key">{{ error }}</p></div></form></section>
        <div class="mb-[18px] mt-[26px] flex items-center justify-between"><h2 class="text-[17px] font-bold">فهرست مسابقات</h2><span class="text-[13px] text-[#7c8984]">{{ tournaments.total.toLocaleString('fa-IR') }} رویداد</span></div>
        <div v-if="tournaments.data.length" class="grid grid-cols-1 gap-[19px] min-[761px]:grid-cols-2 min-[1101px]:grid-cols-3"><TournamentCard v-for="tournament in tournaments.data" :key="tournament.id" :tournament="tournament" /></div><div v-else class="rounded-xl border border-dashed border-[#ccd9ca] bg-[#fafcf8] px-5 py-[50px] text-center"><h2 class="text-lg font-bold">مسابقه‌ای برای نمایش وجود ندارد.</h2></div>
        <nav class="mt-[25px] flex justify-center gap-[18px] text-[#668172]" aria-label="صفحه‌بندی"><Link v-if="tournaments.prev_page_url" :href="tournaments.prev_page_url">صفحهٔ قبل</Link><span>{{ tournaments.current_page }} / {{ tournaments.last_page }}</span><Link v-if="tournaments.next_page_url" :href="tournaments.next_page_url">صفحهٔ بعد</Link></nav>
    </AppLayout>
</template>
